#!/usr/bin/python3

import os
import subprocess
import sys

import click
from google.cloud import storage


@click.command()
@click.argument("conf", default="SPECIAL_NONE_PROVIDED")
def activate(conf):
    """gcloud context switcher"""
    cmd = "gcloud"
    if conf == "SPECIAL_NONE_PROVIDED":
        call = subprocess.run(
            [cmd, "config", "configurations", "list"], capture_output=True
        )
    else:
        call = subprocess.run(
            [cmd, "config", "configurations", "activate", conf], capture_output=True
        )
    print(call.stdout.decode())
    print(call.stderr.decode())


@click.command()
def gcs():
    client = storage.Client()
    for bucket in client.list_buckets():
        print(bucket.name)


if __name__ == "__main__":
    argv0 = os.path.basename(sys.argv[0])
    if argv0 == "gcp":
        activate()
    if argv0 == "gcs":
        gcs()
    else:
        sys.exit(f"{sys.argv[0]} is not a recognized command.")
